spring:
  config:
    import:
      - "optional:nacos:common.yml?namespace=${NACOS_NAMESPACE:}&group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
      - "optional:nacos:${spring.application.name}.yml?namespace=${NACOS_NAMESPACE:}&group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: nacos:8848
        ephemeral: false
        health-check-path: /actuator/health
      config:
        enabled: true
        server-addr: nacos:8848
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        prefix: ${spring.application.name}
        file-extension: yml
        refresh-enabled: true
    discovery:
      client:
        simple:
          enabled: false
  datasource:
    url: jdbc:mysql://list-mysql:3306/list_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USERNAME:music}
    password: ${RABBITMQ_PASSWORD:music123}
    virtual-host: ${RABBITMQ_VHOST:/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
