server:
  port: 8083
spring:
  application:
    name: list-service
  cloud:
    nacos:
      discovery:
        enabled: false
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true
    discovery:
      client:
        simple:
          instances:
            user-service:
              - uri: http://localhost:8081
            meta-service:
              - uri: http://localhost:8082
  datasource:
    url: jdbc:mysql://localhost:3306/list_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Lyy135792468
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
services:
  validation:
    enabled: true
  user:
    base-url: http://localhost:8081
  meta:
    base-url: http://localhost:8082

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
    instances:
      user-service:
        baseConfig: default
      meta-service:
        baseConfig: default
