spring:
  config:
    import:
      - "optional:nacos:common.yml?namespace=${NACOS_NAMESPACE:}&group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
      - "optional:nacos:shared-auth.yml?namespace=${NACOS_NAMESPACE:}&group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
      - "optional:nacos:${spring.application.name}.yml?namespace=${NACOS_NAMESPACE:}&group=${NACOS_GROUP:DEFAULT_GROUP}&refreshEnabled=true"
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: nacos:8848
        ephemeral: false
        health-check-path: /actuator/health
      config:
        enabled: true
        server-addr: nacos:8848
        namespace: ${NACOS_NAMESPACE:}
        group: ${NACOS_GROUP:DEFAULT_GROUP}
        prefix: ${spring.application.name}
        file-extension: yml
        refresh-enabled: true
    gateway:
      routes:
        - id: user-auth
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: meta-service
          uri: lb://meta-service
          predicates:
            - Path=/api/meta/**
        - id: list-service
          uri: lb://list-service
          predicates:
            - Path=/api/favorites/**,/api/playlists/**,/api/playlist-details/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
