spring:
  cloud:
    gateway:
      routes:
        - id: user-auth
          uri: http://user-service:8081
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/api/users/**
        - id: meta-service
          uri: http://meta-service:8082
          predicates:
            - Path=/api/meta/**
        - id: list-service
          uri: http://list-service:8083
          predicates:
            - Path=/api/favorites/**,/api/playlists/**,/api/playlist-details/**