global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: gateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - gateway-service:8090

  - job_name: user-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - user-service:8081
          - user-service-2:8084

  - job_name: meta-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - meta-service:8082

  - job_name: list-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - list-service:8083

